version: 0.2
env:
  variables:
    ECR_REPO: 834549009763.dkr.ecr.us-east-1.amazonaws.com/lks-catalog/bebyschalke
    ECR_REGION: us-east-1
    CONTAINER_NAME: bebyschalke

  parameter-store:
    AWS_ACCESS_KEY: /course-catalog/production/AWS_ACCESS_KEY
    AWS_SECRET_KEY: /course-catalog/production/AWS_SECRET_KEY
    AWS_BUCKET_NAME: /course-catalog/production/AWS_BUCKET_NAME
    AWS_BUCKET_REGION: /course-catalog/production/AWS_BUCKET_REGION
    DB_NAME: /course-catalog/production/DB_NAME
    DB_PASSWORD: /course-catalog/production/DB_PASSWORD
    DB_HOST: /course-catalog/production/DB_HOST # write unit host

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo "Install Dependencies"
      - yum update -y

  pre_build:
    commands:
      - echo "Logging into ECR..."
      - aws ecr get-login-password --region $ECR_REGION | docker login --username AWS --password-stdin 834549009763.dkr.ecr.us-east-1.amazonaws.com || { echo "ECR login failed"; exit 1; }
      - echo "Creating S3 bucket to store dkcfg to be deployed by Beanstalk..."
      - |
        if ! aws s3api head-bucket --bucket $AWS_BUCKET_NAME 2>/dev/null; then
          echo "Bucket does not exist. Creating bucket..."
          aws s3 mb s3://$AWS_BUCKET_NAME || { echo "Failed to create S3 bucket"; exit 1; }
        else
          echo "Bucket already exists. Skipping creation."
        fi
      - aws s3 cp dkcfg s3://$AWS_BUCKET_NAME || { echo "Failed to upload dkcfg"; exit 1; }
      - aws s3 cp Dockerrun.aws.json s3://$AWS_BUCKET_NAME || { echo "Failed to upload Dockerrun.aws.json"; exit 1; }

  build:
    commands:
      - echo "Starting docker..."
      - systemctl start docker
      - echo "Running unit tests..."
      - npm install # Run unit test
      - npm run test 
      - npm run testdev
      - npm install # Run the server
      - npm run start
      - docker build -t lks-catalog/bebyschalke:latest . # Run with docker
      - docker run -d -p 8080:8000 --name=course-catalog-container lks-catalog/bebyschalke:latest

  post_build:
    commands:
      - echo "Pushing the image to ECR..."
      - docker tag lks-catalog/bebyschalke:latest 834549009763.dkr.ecr.us-east-1.amazonaws.com/lks-catalog/bebyschalke:latest || { echo "Failed to tag Docker image"; exit 1; }
      - docker push 834549009763.dkr.ecr.us-east-1.amazonaws.com/lks-catalog/bebyschalke:latest || { echo "Failed to push Docker image to ECR"; exit 1; }
      - echo "Image has been pushed into ECR..."
      - printf '[{"name":"%s","imageUri":"%s "}]' $CONTAINER_NAME ${ECR_REPO}:latest > imagedefinitions.json
      - echo "Build complete."

reports:
  test-report:
    files:
      - 'report/test-result.xml'
    file-format: JUNITXML

artifacts:
  files:
    - imagedefinitions.json